// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"time"
)

type Chat struct {
	ID               string
	UserID           string
	InitialMessageID string
	Status           string
	TokenUsage       int32
	Model            string
	ModelMaxTokens   int32
	Temperature      float64
	TopP             float64
	N                int32
	Stop             string
	MaxTokens        int32
	PresencePenalty  float64
	FrequencyPenalty float64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Message struct {
	ID        string
	ChatID    string
	Role      string
	Content   string
	Tokens    int32
	Model     string
	Erased    bool
	OrderMsg  int32
	CreatedAt time.Time
}
