POST http://localhost:8081/chat HTTP/1.1
Content-Type: application/json
Authorization: 123456

{
    "user_id": "1",
    "user_message": "Olá, qual é o seu nome?"
}

###

POST http://localhost:8081/chat HTTP/1.1
Content-Type: application/json
Authorization: 123456

{
    "chat_id": "a14fc851-7e95-49b5-a5b5-44479434becd",
    "user_id": "1",
    "user_message": "continue"
}