GET http://localhost:3000/api/hello

@token = eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..XnskWOEMEV-7teRh.Kfx1uSJGTBQzhMdy_gaDlCNz_Lz9UvSeKBCMBPHdKOZmN-WoZZRkOrFwmdbBDfKjRg7Y48VnP_9-K5xkUP4H6nGeCvc9ovRvuKlGFKm2ja_E3CjYjGLHRFLjrcYIu3qb9YPNYIZ41leztsY20HPbtQ7lyxUjKYwjDKvU3e59hvg8QNjc3dQyglaCvzs.TIHDzzl-FrxwwH3hKFr1Wg
###
POST http://localhost:3000/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "message": "Hello World3"
}

###
GET http://localhost:3000/api/chats
Authorization: Bearer {{token}}

###
@chatId = b1a23a46-f7f6-4c45-8435-f9173a1b525f

GET http://localhost:3000/api/chats/{{chatId}}/messages
Authorization: Bearer {{token}}

###
POST http://localhost:3000/api/chats/{{chatId}}/messages
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "message": "Estou testando a API 2222"
}

###
@messageId = d56cf557-17b5-4a9f-ac58-1f0be4bccbe3
GET http://localhost:3000/api/messages/{{messageId}}/events
Authorization: Bearer {{token}}

###
POST http://localhost:3000/api/generate-token
Content-Type: application/json

{

}

###
GET http://localhost:3000/api/event-stream